# Generated by Django 2.0.2 on 2022-09-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nombre del grupo:')),
                ('coordinator', models.CharField(max_length=50, null=True, verbose_name='Coordinador(a) del grupo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Título')),
                ('image', models.FileField(null=True, upload_to='', verbose_name='Imagen')),
                ('banner', models.FileField(null=True, upload_to='', verbose_name='Banner')),
                ('description', models.TextField(null=True, verbose_name='Descripción')),
                ('content', models.TextField(null=True, verbose_name='Contenido de la noticia')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('username', models.CharField(max_length=50, null=True, verbose_name='Nombre de usuario:')),
                ('password', models.CharField(max_length=50, null=True, verbose_name='Contraseña:')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nombre:')),
                ('lastname', models.CharField(max_length=50, null=True, verbose_name='Apellidos::')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Correo electrónico:')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['lastname'],
            },
        ),
    ]
