# Generated by Django 2.0.2 on 2022-09-01 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conv', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nivel', models.CharField(max_length=10, null=True, verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Atributos_otra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('tipo', models.CharField(max_length=100, null=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos otra universidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=100, null=True, verbose_name='Tipo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='categoriaAdyacente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.TextField(max_length=400, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria Adyacente',
                'verbose_name_plural': 'Categorias Adyacentes de produccion cientifica',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='categoriaPrincipal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.TextField(max_length=400, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria Principal',
                'verbose_name_plural': 'Categorias Principales de produccion cientifica',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del certificado')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('description', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='coordinadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('id_semillero', models.CharField(max_length=100, null=True, verbose_name='Semillero')),
            ],
            options={
                'verbose_name': 'Coordinador',
                'verbose_name_plural': 'Coordinadores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del integrante')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre del integrante')),
                ('lastname', models.CharField(max_length=100, null=True, verbose_name='Apellidos del integrante')),
                ('document', models.CharField(max_length=12, null=True, verbose_name='Documento de identidad')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Telefono')),
                ('aditional', models.CharField(max_length=100, null=True, verbose_name='Informacion Adicional')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Linea de investigación')),
                ('description', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Línea',
                'verbose_name_plural': 'Líneas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LineaSemillero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('id_coo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Integrante', verbose_name='Coordinador')),
                ('id_linea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Linea', verbose_name='Id de la línea')),
            ],
            options={
                'verbose_name': 'Línea por coordinador',
                'verbose_name_plural': 'Líneas por coordinador',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('descripcion', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Mes',
                'verbose_name_plural': 'Meses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Participante2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('status', models.IntegerField(default=1, verbose_name='Estado')),
                ('joined', models.DateField(null=True, verbose_name='Fecha de ingreso')),
                ('id_integrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Integrante', verbose_name='Integrante')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='produccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('archivo', models.FileField(upload_to='', verbose_name='Archivo adjunto')),
                ('año', models.CharField(max_length=100, null=True, verbose_name='Año de publicación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.categoriaAdyacente', verbose_name='Categoria adyacente')),
                ('mes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Mes', verbose_name='Mes de publicación')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.Proyectos', verbose_name='Proyecto Asociado')),
            ],
            options={
                'verbose_name': 'Produccion Cientifica',
                'verbose_name_plural': 'Producciones Cientificas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre del rol')),
                ('description', models.TextField(null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Semillero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('description', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
                ('history', models.TextField(null=True, verbose_name='Antesedentes')),
                ('mision', models.TextField(null=True, verbose_name='Misión')),
                ('vision', models.TextField(null=True, verbose_name='Visión')),
                ('goals', models.TextField(null=True, verbose_name='Objetivos')),
                ('mail', models.TextField(null=True, verbose_name='Correo de contacto')),
                ('image', models.FileField(default='/logo_udea.png', null=True, upload_to='', verbose_name='Imagen del semillero')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Integrante', verbose_name='coordinador')),
            ],
            options={
                'verbose_name': 'Semillero',
                'verbose_name_plural': 'Semilleros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la validación')),
                ('fecha_expedicion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('certificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Certificado', verbose_name='Certificado')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Participante2', verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Validacion',
                'verbose_name_plural': 'Validaciones',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='produccion',
            name='semillero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.Semillero', verbose_name='Semillero'),
        ),
        migrations.AddField(
            model_name='participante2',
            name='id_semillero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Semillero', verbose_name='Semillero'),
        ),
        migrations.AddField(
            model_name='participante2',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Rol', verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='lineasemillero',
            name='id_participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Participante2', verbose_name='Participante'),
        ),
        migrations.AddField(
            model_name='coordinadores',
            name='Integrante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Integrante', verbose_name='Integrante'),
        ),
        migrations.AddField(
            model_name='coordinadores',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriaadyacente',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.categoriaPrincipal', verbose_name='Categoria Principal'),
        ),
        migrations.AddField(
            model_name='atributos_otra',
            name='id_estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Integrante', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='atributos_otra',
            name='id_participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Participante2', verbose_name='Participante'),
        ),
        migrations.AddField(
            model_name='atributos',
            name='id_estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Integrante', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='atributos',
            name='id_participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Participante2', verbose_name='Participante'),
        ),
        migrations.AddField(
            model_name='atributos',
            name='id_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Career', verbose_name='Programa'),
        ),
    ]
