# Generated by Django 2.0.2 on 2022-09-01 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='id_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Grupo', verbose_name='Grupo de investigacion'),
        ),
    ]
