# Generated by Django 2.0.2 on 2022-09-01 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre de la convocatoria')),
                ('description', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
                ('opened', models.DateField(null=True, verbose_name='Fecha de apertura')),
                ('closed', models.DateField(null=True, verbose_name='Fecha de cierre')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'ordering': ['closed'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('documento', models.FileField(null=True, upload_to='', verbose_name='Documento')),
                ('description', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
                ('tipo', models.PositiveSmallIntegerField(null=True, verbose_name='Tipo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('id_conv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.Convocatoria')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['id_conv'],
            },
        ),
        migrations.CreateModel(
            name='Documento_Adjunto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('documento', models.FileField(null=True, upload_to='', verbose_name='Documento')),
                ('comentarios', models.FileField(null=True, upload_to='', verbose_name='Comentarios')),
                ('estado', models.CharField(max_length=100, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('id_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.Documento', verbose_name='Documento del semillero')),
            ],
            options={
                'verbose_name': 'Documento Adjunto',
                'verbose_name_plural': 'Documentos Adjuntos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documentos_proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('tipo', models.CharField(max_length=10, null=True, verbose_name='Tipo')),
                ('documento', models.FileField(null=True, upload_to='', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes de proyecto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documentos_proyecto_2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
                ('documento', models.FileField(null=True, upload_to='', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos de proyecto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='observaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
                ('documento', models.FileField(null=True, upload_to='', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Observacion',
                'verbose_name_plural': 'Observaciones a reporte',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estado', models.CharField(max_length=10, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('id_convocatoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.Convocatoria', verbose_name='Convocatoria')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('codigo', models.CharField(max_length=100, null=True, verbose_name='Codigo')),
                ('estado', models.CharField(max_length=10, null=True, verbose_name='Estado')),
                ('porcentaje', models.CharField(max_length=20, null=True, verbose_name='Porcentaje de avance')),
                ('description', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
                ('start', models.DateField(null=True, verbose_name='Fecha de inicio')),
                ('closed', models.DateField(null=True, verbose_name='Fecha de cierre')),
                ('convocatoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.Convocatoria')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='documentos_proyecto_2',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.Proyectos'),
        ),
        migrations.AddField(
            model_name='documentos_proyecto',
            name='observaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.observaciones'),
        ),
        migrations.AddField(
            model_name='documentos_proyecto',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.Proyectos'),
        ),
        migrations.AddField(
            model_name='documento_adjunto',
            name='id_participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.Participante', verbose_name='Participante'),
        ),
        migrations.AddField(
            model_name='documento_adjunto',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
