# Generated by Django 2.0.2 on 2022-09-01 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
        ('conv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='id_semillero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Semillero', verbose_name='Semillero Participante'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='semillero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Semillero'),
        ),
    ]
